config/routes.rb
Rails.application.routes.draw do

devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: "home#top"


get "/home/about" => "home#about", as: "about"
resources :diarys, only: [:new, :index, :show, :create, :edit, :update]
resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  def get_image(width, height)
    unless profile_image.attached?
      "images.png"
    else
     image.variant(resize_to_limit: [width, height]).processed
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :image
  has_many :diarys, dependent: :destroy
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      "noimage.jpg"
    else
     profile_image.variant(resize_to_limit: [width, height]).processed
    end
  end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller

  def after_sign_in_path_for(resource)
    about_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/diarys_controller.rb
class DiarysController < ApplicationController
  
  def new
    @diary = Diary.new
  end
  
  def create
    @diary = Diary.new(diary_params)
    @diary.user_id = current_user.id
    @diary.save
    redirect_to user_path(@user.id)
  end 

  def index
    @diarys = Diary.all
    @user = current_user
  end

  def show
    @diary = Diary.find(params[:id])
  end
  
  def edit
    @diary = Diary.find(params[:id])
  end 
  
  def update
    @diary = Diary.find(params[:id])
    @diary.update(diary_params)
    redirect_to diary_path(@diary.id)
  end 
  
  private
  def diary_params
    params.require(:diary).permit(:title, :body, :image)
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
  end

  def about
  end



end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end 
  
  def index
    @users = User.all
  end 
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :animal_name, :profile_image, :introduction)
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diarys_helper.rb
module DiarysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diarys/edit.html.erb
<h2>Editing screen</h2>

<%= form_with model: @diary do |f| 
<!--%= form_with model: @diary, url: diary_path(@diary.id), method: :patch do |f| %>-->


<p><h4>image</h4></p>
    <p><%= f.file_field :image, accept : "image/*" %></p>

 <p><h4>title</h4></p>
    <p><%= f.text_field :title %></p>

 <p><h4>diary</h4></p>
    <p><%= f.text_area :body %></p>
    
<% end %>

app/views/diarys/index.html.erb
<%= render 'users/userinfo', user: @user %>

<h2>Diary</h2>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>title</th>
    </tr>
  </thead>
  
  <tbody>
    <% @diarys.each do |diary| %>
    <tr>
      <td><%= link_to diary_path(diary.id) do %>
            <%= image_tag diary.get_image(50,50) %>
          <% end %></td>
          
      <td><%= diary.title %></td>
      <td><%= link_to "show", diary_path(diary.id) %></td>
    </tr>
  </tbody>
</table>

app/views/diarys/new.html.erb
<h2>Today's diary　<i class="fa-solid fa-pen-nib"></i></h2>
<% form_with model: @diary do |f| %>

  <h4>image</h4>
  <%= f.file_field :image, accept : "image/*" %>

  <h4>title</h4>
  <%= f.text_field :title %>

  <h4>diary</h4>
  <%= f.text_area :body %>

  <!--<h4>day</h4>-->
  <!--%= @diary.created_at.strftime('%Y/%m/%d') %>-->
  
  <% f.submit '投稿' %>
<% end %>

app/views/diarys/show.html.erb
<h2>Diary</h2>
  <table class="table">
    <tbody>
      <tr>
        <td><%= image_tag @diary.get_image(100,100) %></td>
        <td><%= diary.title %></td>
        <td></td>
        <td><%= diary.body %></td>
        <td> <%= @diary.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
    </tbody>
  </table>

app/views/home/about.html.erb
<h1><i class="fa-solid fa-bone"></i> うちの子の日記 <i class="fa-solid fa-bone"></i></h1>

<p>我が子の日々の記録</p>

app/views/home/top.html.erb
<h1><i class="fa-solid fa-paw"></i>うちの子の日記<i class="fa-solid fa-paw"></i></h1>


<p>〜　我が子の毎日の記録　〜</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Animal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/01e2407594.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <% if user_signed_in? %>
      <li>
        <%= link_to user_path(current_user.id) do %>
          <i class="fa-solid fa-door-closed"></i> Home
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa-solid fa-arrow-right-from-bracket"></i> Log out
        <% end %>
      </li>
      <li>
        <%= link_to new_diary_path do %>
          <i class="fa-solid fa-pen-nib"></i> Diary
        <% end %>
      </li>
    <% else %>
      
      <li>
        <%= link_to root_path do %>
          <i class="fa-solid fa-door-closed"></i> Home
        <% end %>
      </li>
      
      <li>
        <%= link_to about_path do %>
          <i class="fa-solid fa-bowl-food"></i> About
        <% end 
      </li>
      
    <% end %>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_userinfo.html.erb
<h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
 <table class="table">
   <tbody>
     <tr>
       <th>name</th>
       <th><%= user.name %></th>
     </tr>
     <tr>
       <th>animal name</th>
       <th><%= user.animal_name %></th>
     </tr>
     <tr>
       <th>introduction</th>
       <th><%= user.introduction %></th>
     </tr>
     
     <% if user.id == current_user.id %>
       <%= link_to edit_user_path(current_user.id) do %>
         <i class="fa-solid fa-gear"></i>
       <% end %>
       <% else %>
       <%= link_to edit_user_path(user.id) do %>
         <i class="fa-solid fa-gear"></i>
       <% end %>
    <% end %>
    
   </tbody>
 </table>
 

app/views/users/edit.html.erb
<h1>User info</h1>
<%= form_with model: @user do |f| %>
  
  
  <p><label for="user_name">name</label></p>
  <p><%= f.text_field :name, autofocus: true, id:"user_name", placeholder:"name" %></p>
  
  
  <p><label for="animal_name">pet name</label></p>
  <p><%= f.text_field :animal_name, autofocus: true, id:"animal_name", placeholder:"animal name" %></p>
  
  <p><label for="user_image">profile image</label></p>
  <p><%= f.file_field :profile_image, placeholder: "profile image", accept: "image/*" %></p>
  
  <p><label for="user_introduction">introduction</label></p>
  <p><%= f.text_area :introduction, autofocus: true, id:"user_introduction", placeholder:"introduction" %></p>
  
  <%= f.submit "Update User" %>
  
<% end %>

app/views/users/index.html.erb
<%= render 'userinfo', user: @user %>
<h2>Users</h2>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th>animal name</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image(50,50) %></td>
      <td><%= user.name %></td>
      <td><%= user.animal_name %></td>
      <td><%= link_to "show", user_path(user.id) %></td>
    </tr>
  </tbody>
</table>
 

  

app/views/users/show.html.erb
<%= render 'userinfo', user: @user %>

<h2>Diary</h2>

<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>Day</th>
      <th>Title</th>
      <th>Diary</th>
    </tr>
  </thead>

  <tbody>

  </tbody>
</table>